package com.liu.eemrsagent.reporttrend;

public enum ReportTrendErrorCode {
    REPORT_NOT_FOUND,
    REPORT_DECRYPT_FAILED,
    REPORT_PARSE_FAILED,
    INDICATOR_NORMALIZE_FAILED,
    INSUFFICIENT_REPORT_DATA,
    CLOUD_PAYLOAD_PRIVACY_VIOLATION,
    CLOUD_MODEL_FAILED,
    CLOUD_RESPONSE_INVALID,
    RESULT_ENCRYPT_FAILED,
    UNKNOWN_ERROR
}
