package com.liu.eemrsagent.reporttrend;

public enum ReportTrendErrorCode {
    REPORT_NOT_FOUND,
    REPORT_DECRYPT_FAILED,
    REPORT_PARSE_FAILED,
    INDICATOR_NORMALIZE_FAILED,
    INSUFFICIENT_REPORT_DATA,
    CLOUD_PAYLOAD_PRIVACY_VIOLATION,
    CLOUD_MODEL_FAILED,
    CLOUD_CONNECT_TIMEOUT,
    CLOUD_READ_TIMEOUT,
    CLOUD_HTTP_ERROR,
    CLOUD_RATE_LIMITED,
    CLOUD_RESPONSE_EMPTY,
    CLOUD_RESPONSE_INVALID,
    CLOUD_RESPONSE_JSON_INVALID,
    CLOUD_RESPONSE_SCHEMA_MISMATCH,
    RESULT_ENCRYPT_FAILED,
    UNKNOWN_ERROR
}
