-- Unified Agent Trace Harness schema for eemrs-agent-server.
-- Rollback example:
-- DROP TABLE IF EXISTS tool_call;
-- DROP TABLE IF EXISTS agent_step;
-- DROP TABLE IF EXISTS agent_run;

CREATE TABLE IF NOT EXISTS agent_run (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    schema_version INT NOT NULL DEFAULT 1,
    trace_id VARCHAR(80) NOT NULL COMMENT 'Cross-service trace id',
    run_id VARCHAR(80) NOT NULL COMMENT 'One complete agent run id',
    session_id VARCHAR(100) NULL COMMENT 'Conversation/session id',
    user_id_hash VARCHAR(128) NULL COMMENT 'Irreversible user id hash',
    agent_name VARCHAR(100) NULL,
    request_type VARCHAR(100) NULL,
    prompt_version VARCHAR(100) NULL,
    rag_version VARCHAR(100) NULL,
    model_name VARCHAR(100) NULL,
    status VARCHAR(30) NOT NULL,
    started_at DATETIME NOT NULL,
    ended_at DATETIME NULL,
    total_latency_ms BIGINT NULL,
    prompt_tokens INT NULL,
    completion_tokens INT NULL,
    total_tokens INT NULL,
    estimated_cost DECIMAL(18,6) NULL,
    cost_currency VARCHAR(10) NULL,
    cost_config_version VARCHAR(50) NULL,
    final_output_summary TEXT NULL,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(1000) NULL,
    metadata_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_agent_run_run_id (run_id),
    KEY idx_agent_run_trace_id (trace_id),
    KEY idx_agent_run_session_id (session_id),
    KEY idx_agent_run_user_id_hash (user_id_hash),
    KEY idx_agent_run_status (status),
    KEY idx_agent_run_created_at (created_at),
    KEY idx_agent_run_session_created (session_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent run trace root';

CREATE TABLE IF NOT EXISTS agent_step (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    schema_version INT NOT NULL DEFAULT 1,
    trace_id VARCHAR(80) NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    step_id VARCHAR(80) NOT NULL,
    parent_step_id VARCHAR(80) NULL,
    sequence_no INT NOT NULL,
    step_type VARCHAR(60) NOT NULL,
    step_name VARCHAR(120) NULL,
    component VARCHAR(100) NULL,
    service_name VARCHAR(100) NULL,
    model_name VARCHAR(100) NULL,
    prompt_version VARCHAR(100) NULL,
    input_summary TEXT NULL,
    output_summary TEXT NULL,
    input_hash VARCHAR(128) NULL,
    output_hash VARCHAR(128) NULL,
    request_payload_json LONGTEXT NULL,
    response_payload_json LONGTEXT NULL,
    metadata_json LONGTEXT NULL,
    status VARCHAR(30) NOT NULL,
    started_at DATETIME NOT NULL,
    ended_at DATETIME NULL,
    latency_ms BIGINT NULL,
    prompt_tokens INT NULL,
    completion_tokens INT NULL,
    total_tokens INT NULL,
    estimated_cost DECIMAL(18,6) NULL,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_agent_step_step_id (step_id),
    KEY idx_agent_step_run_id (run_id),
    KEY idx_agent_step_run_sequence (run_id, sequence_no),
    KEY idx_agent_step_parent_step_id (parent_step_id),
    KEY idx_agent_step_step_type (step_type),
    KEY idx_agent_step_status (status),
    KEY idx_agent_step_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent execution steps';

CREATE TABLE IF NOT EXISTS tool_call (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    schema_version INT NOT NULL DEFAULT 1,
    trace_id VARCHAR(80) NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    step_id VARCHAR(80) NULL,
    tool_call_id VARCHAR(80) NOT NULL,
    tool_name VARCHAR(120) NOT NULL,
    tool_type VARCHAR(60) NULL,
    target_service VARCHAR(120) NULL,
    target_endpoint VARCHAR(255) NULL,
    request_summary TEXT NULL,
    response_summary TEXT NULL,
    request_hash VARCHAR(128) NULL,
    response_hash VARCHAR(128) NULL,
    request_payload_json LONGTEXT NULL,
    response_payload_json LONGTEXT NULL,
    http_status INT NULL,
    status VARCHAR(30) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    started_at DATETIME NOT NULL,
    ended_at DATETIME NULL,
    latency_ms BIGINT NULL,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(1000) NULL,
    metadata_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_tool_call_id (tool_call_id),
    KEY idx_tool_call_run_id (run_id),
    KEY idx_tool_call_step_id (step_id),
    KEY idx_tool_call_tool_name (tool_name),
    KEY idx_tool_call_status (status),
    KEY idx_tool_call_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent external tool calls';
