CREATE TABLE IF NOT EXISTS agent_medical_record_draft (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    patient_id BIGINT NULL,
    patient_id_number VARCHAR(64) NULL,
    session_id VARCHAR(100) NULL,
    consultation_mode VARCHAR(20) NOT NULL DEFAULT 'deep',
    source_type VARCHAR(50) NOT NULL DEFAULT 'DEEP_PRE_CONSULTATION',
    chief_complaint VARCHAR(1000) NULL,
    present_illness_history TEXT NULL,
    recommended_department VARCHAR(255) NULL,
    urgency VARCHAR(50) NULL,
    consultation_summary LONGTEXT NULL,
    record_json LONGTEXT NOT NULL,
    ai_record_json LONGTEXT NULL,
    edited_record_json LONGTEXT NULL,
    raw_model_reply LONGTEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'GENERATED',
    doctor_id_number VARCHAR(64) NULL,
    appointment_id VARCHAR(100) NULL,
    model_name VARCHAR(100) NULL,
    prompt_version VARCHAR(100) NULL,
    trace_id VARCHAR(100) NULL,
    first_reviewed_at DATETIME NULL,
    completed_at DATETIME NULL,
    applied_at DATETIME NULL,
    applied_record_hash VARCHAR(128) NULL,
    created_by VARCHAR(100) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_agent_draft_patient_mode_deleted_created (patient_id, consultation_mode, deleted, created_at),
    INDEX idx_agent_draft_patient_id_number_created (patient_id_number, consultation_mode, deleted, created_at),
    INDEX idx_agent_draft_doctor_status_created (doctor_id_number, status, created_at),
    INDEX idx_agent_draft_session (session_id)
);

CREATE TABLE IF NOT EXISTS agent_medical_record_draft_audit (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    draft_id BIGINT NOT NULL,
    doctor_id_number VARCHAR(64) NOT NULL,
    action VARCHAR(40) NOT NULL,
    before_json LONGTEXT NULL,
    after_json LONGTEXT NULL,
    reject_reason VARCHAR(1000) NULL,
    comment VARCHAR(1000) NULL,
    action_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trace_id VARCHAR(100) NULL,
    INDEX idx_agent_draft_audit_draft_time (draft_id, action_time),
    INDEX idx_agent_draft_audit_doctor_action (doctor_id_number, action, action_time)
);
