package com.liu.eemrsagent.trace;

public enum TraceErrorCode {
    TRACE_PERSIST_FAILED,
    TRACE_SERIALIZE_FAILED,
    TRACE_REDACT_FAILED,
    TRACE_CONTEXT_MISSING,
    RAG_TIMEOUT,
    RAG_HTTP_ERROR,
    RAG_RESPONSE_INVALID,
    MODEL_TIMEOUT,
    MODEL_HTTP_ERROR,
    MODEL_RESPONSE_INVALID,
    POST_PROCESS_FAILED,
    TOOL_TIMEOUT,
    TOOL_HTTP_ERROR,
    TOOL_BUSINESS_ERROR,
    UNKNOWN_ERROR
}
